# Generated by Django 4.0.4 on 2022-05-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorite',
            new_name='genres',
        ),
        migrations.RemoveField(
            model_name='user',
            name='genre',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('남', '남'), ('여', '여')], default='남', max_length=5),
        ),
    ]
