# Generated by Django 4.0.4 on 2022-05-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_rename_favorite_user_genres_remove_user_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'mail'), ('female', 'female')], default='male', max_length=10),
        ),
    ]
