# Generated by Django 4.0.4 on 2022-05-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='day',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='month',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.IntegerField(default=2000, max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10),
        ),
    ]
