# Generated by Django 4.0.4 on 2022-05-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_user_day_user_month_user_year_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
