# Generated by Django 4.0.4 on 2022-04-18 06:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='img/'),),
                (
                    'date',
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    'user_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'db_table': 'board',},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'date',
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ('content', models.TextField()),
                (
                    'board_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='board.board',
                    ),
                ),
            ],
            options={'db_table': 'comment',},
        ),
    ]
