# Generated by Django 4.0.4 on 2022-04-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='response',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='No', max_length=5),
        ),
    ]
