# Generated by Django 3.2 on 2022-04-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_board_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='response',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=5),
        ),
    ]
