# Generated by Django 4.0.4 on 2022-05-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_board_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='익명의 니모션', max_length=10),
        ),
    ]
