# Generated by Django 4.0.4 on 2022-05-07 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_comment_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='author',
        ),
    ]
