# Generated by Django 4.0.4 on 2022-05-09 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_rename_username_comment_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='NULL', max_length=1000, null=True)),
                ('genres', models.CharField(default='NULL', max_length=1000, null=True)),
                ('img', models.TextField(default='NULL', null=True)),
            ],
            options={
                'db_table': 'movie_s',
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(default='NULL', max_length=150, null=True)),
                ('rating', models.FloatField(default='NULL', null=True)),
                ('movieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.movie')),
            ],
            options={
                'db_table': 'rating_s',
            },
        ),
    ]
