# Generated by Django 4.0.4 on 2022-05-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_movie_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='movieId',
            field=models.IntegerField(),
        ),
    ]
