# Generated by Django 4.0.4 on 2022-05-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_alter_notice_content_alter_ratings_movieid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ratings',
            constraint=models.UniqueConstraint(fields=('userid', 'movieId'), name='unique rating'),
        ),
    ]
